compressionLevel: mixed

enableGlobalCache: false

nodeLinker: node-modules

packageExtensions:
  nuxt@*:
    peerDependencies:
      vite: ^4.4.9
  vitest-environment-nuxt@*:
    peerDependencies:
      h3: ^1.10.1
      vite: ^4.4.9
      vue: ^3.3.4
      vue-router: ^4.2.5

yarnPath: .yarn/releases/yarn-4.2.2.cjs
