nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-3.6.3.cjs

packageExtensions:
    'nuxt@*':
        peerDependencies:
            vite: '^4.4.9'
    'vitest-environment-nuxt@*':
        peerDependencies:
            vite: '^4.4.9'
            h3: '^1.10.1'
            vue: '^3.3.4'
            vue-router: '^4.2.5'
